spark.master                     yarn
spark.submit.deployMode          client
spark.driver.memory              1g
spark.executor.memory            512m
spark.executor.cores             1
spark.sql.shuffle.partitions     20
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs:///spark-logs
spark.sql.adaptive.enabled       true
